services:
  - type: web
    name: truestate-retail-app
    env: python
    region: singapore
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      cd frontend
      npm install
      npm run build
      cd ..
      python backend/src/manage.py collectstatic --noinput
    startCommand: |
      cd backend/src
      python manage.py migrate --noinput
      gunicorn core.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
